name: proyecto_laplanchita
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  awesome_snackbar_content: ^0.1.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  path_provider: ^2.0.14
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fondo.jpg
    - assets/logo.jpg
    - assets/fondo_empanadas.jpg
    - assets/La_Planchita_Logo.png
    - assets/bombilla.gif
    - assets/empanada_papa_carne.png
    - assets/empanada_pollo.png
    - assets/empanada_cerdo.png
    - assets/empanada_res.png
    - assets/empanada_pollo_champ.png
    - assets/empanada_salchicha_queso.png
    - assets/empanada_hawaiana.png
    - assets/empanada_ranchera.png
    - assets/hamburguesa_res.png
    - assets/hamburguesa_pollo.png
    - assets/hamburguesa_plancha.png